### PR TITLE
#159053954 Configure postgres database

### PR DESCRIPTION
**Pull request by ronaldndirangu**
#### What does this PR do?
Setup Postgres database and add .env example

#### Description of tasks to be completed
Ensure that Postgres database is used to store the application data

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans.git
```
```sh
$ git checkout -b ch-configure-postgresdb-159053954
```
```sh
$ cd ah-titans/authors
```

> Add **.env** file and copy **example.env** content.
> Add your local database configuration settings to your **.env** file

```sh
$ source .env
```
```sh
$ python3.6 -m venv venv
```
```sh
$ source venv/bin/activate
```
```sh
$ pip install -r requirements.txt
```
```sh
$ python manage.py makemigrations
```
```sh
$ python manage.py runserver
```

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#159053954](https://www.pivotaltracker.com/story/show/159053954)

### CODE REVIEW

**Comment by janetnim** [comment]
looks good

**Comment by migot01** [comment]
Well detailed

**Comment by dcDalin** [comment]
Looks good

**Comment by chepmanu** [comment]
Looks good to me, good code!

**Comment by petermwash** [comment]
It's well detailed. Keep up the good work.

**Pull request merged**
