### PR TITLE
#159330641 Add base template and templates of merged feature

### PR DESCRIPTION
**Pull request by petermwash**
#### What does this PR do?
Seeks to merge the ch-add-base-template-159330641 branch into the develop branch.

#### Description of tasks to be completed
Create the base mock template and the mock template for the already merged features.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans.git
```
```sh
$ git checkout ch-add-base-template-159330641
```
```sh
$ cd ah-titans/authors/templates
```

> Then you can double-click on the individual templates to view them on the browser.`
> You should be able to see the pages like the ones shown below.

>Base template

screen shot 2018-07-31 at 12 35 32

>Login template

screen shot 2018-07-31 at 10 58 49

>Signup template

screen shot 2018-07-30 at 19 46 10

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#159330641](https://www.pivotaltracker.com/story/show/159330641)

### CODE REVIEW

**Comment by janetnim** [comment]
Is there a way you can add the logo to the header and padding/left margin to the header

**Comment by petermwash** [comment]
@janetnim Yeah sure, Let me check on that.

**Comment by johnmusiu** [comment]
Can you make the sign in buttons have different colors? Like green for login, red for google and blue for facebook

**Comment by migot01** [comment]
.DS_store file ought to be in gitignore

**Comment by dcDalin** [comment]
Impressive job, well done @petermwash. However, I think the social links on the login page would look so much better if they were on the same row. Please considering tweaking your CSS so as to allow this.

**Comment by chepmanu** [comment]
It is nice but I think the option for logging in with twitter should also be provided apart from facebook and google.

**Comment by petermwash** [comment]
@johnmusiu  @dcDalin @dcDalin Feedback implemented. You can do another review now.

**Comment by petermwash** [comment]
@chepmanu I think for now we are working on login with Google and Facebook, we might consider adding the login with Twiter later as we move on with the project.

**Comment by ronaldndirangu** [comment]
I think the @2014 in the footer should be changed to @2018.

**Comment by petermwash** [comment]
@ronaldndirangu Thanks for pointing that out, it is now Fixed.

**Review by ridgekimani — APPROVED** [review]

**Pull request merged**
